# Generated by Django 5.2.17 on 2026-08-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(default='17:00'),
        ),
    ]
