# Generated by Django 5.2.4 on 2026-08-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_return_time'),
        ('vehicles', '0002_vehicleunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='handover_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='vehicles.vehicleunit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('awaiting_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('waiting_for_pickup', 'Waiting for Pickup'), ('active', 'Active Rental'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
    ]
