# Generated by Django 5.2.4 on 2026-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_handover_time_booking_vehicle_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='identity_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
