# Generated by Django 5.2.17 on 2026-08-08 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_identity_snapshot'),
        ('vehicles', '0002_vehicleunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_time_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_unit_status',
            field=models.CharField(blank=True, help_text='Post-return status of the vehicle unit (available/maintenance/inactive). Must be recorded before completing the transaction.', max_length=20),
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_assignments', to=settings.AUTH_USER_MODEL)),
                ('new_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_assignments', to='vehicles.vehicleunit')),
                ('previous_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to='vehicles.vehicleunit')),
            ],
            options={
                'verbose_name_plural': 'Assignment histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
