# Generated by Django 5.2.17 on 2026-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_return_time_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='return_unit_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], help_text='Post-return status of the vehicle unit (available/maintenance/inactive). Must be recorded before completing the transaction.', max_length=20),
        ),
    ]
