# Generated by Django 5.2.17 on 2026-08-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_return_unit_status'),
        ('vehicles', '0007_plate_number_format_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(help_text='Original vehicle.  Preserved for audit even if the vehicle is later removed from the fleet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='vehicles.vehicle'),
        ),
    ]
