# Generated by Django 5.2.17 on 2026-08-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_vehicle'),
        ('vehicles', '0007_plate_number_format_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenthistory',
            name='new_unit',
            field=models.ForeignKey(help_text='Assigned unit. Preserved for audit even if the unit is later removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to='vehicles.vehicleunit'),
        ),
    ]
