# Generated by Django 5.2.4 on 2026-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_assignmenthistory_new_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='repayment_requested',
            field=models.BooleanField(default=False, help_text='Set to True when customer requests a new payment attempt after expiry.'),
        ),
    ]
