# Generated by Django 5.2.4 on 2026-08-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_repayment_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monetary discount applied to this booking (snapshot at booking time).', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied to this booking (snapshot at booking time).', max_digits=5),
        ),
    ]
