# Generated by Django 5.2.4 on 2026-08-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_discount_amount_booking_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('awaiting_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('waiting_for_pickup', 'Waiting for Pickup'), ('active', 'Active Rental'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
    ]
