# Generated by Django 5.2.4 on 2026-08-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='repayment_requested',
        ),
    ]
