# Generated by Django 5.2.17 on 2026-08-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_booking_repayment_requested'),
        ('vehicles', '0010_vehicle_discount_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenthistory',
            name='new_unit',
            field=models.ForeignKey(help_text='Assigned unit.  Deleting a unit referenced by assignment history is blocked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_assignments', to='vehicles.vehicleunit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(help_text='Original vehicle.  Deleting a vehicle that is referenced by a booking is blocked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_unit',
            field=models.ForeignKey(blank=True, help_text='Assigned unit.  Deleting a unit referenced by a booking is blocked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicles.vehicleunit'),
        ),
    ]
