# Generated by Django 5.2.17 on 2026-08-08 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_booking_return_time_actual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_submitted', 'Booking Request Submitted'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('payment_required', 'Payment Required'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('booking_confirmed', 'Booking Confirmed'), ('reschedule_requested', 'Reschedule Requested'), ('reschedule_approved', 'Reschedule Approved'), ('reschedule_rejected', 'Reschedule Rejected'), ('unit_assigned', 'Vehicle Unit Assigned'), ('unit_changed', 'Vehicle Unit Changed'), ('pickup_reminder', 'Pickup Reminder'), ('rental_activated', 'Rental Activated'), ('extension_requested', 'Extension Requested'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected'), ('vehicle_returned', 'Vehicle Returned'), ('additional_payment_required', 'Additional Payment Required'), ('transaction_completed', 'Transaction Completed')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_admin_notification', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['is_read', 'user'], name='core_notifi_is_read_8bc917_idx'), models.Index(fields=['is_admin_notification', '-created_at'], name='core_notifi_is_admi_433029_idx')],
            },
        ),
    ]
