# Generated by Django 5.2.4 on 2026-08-10 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_return_unit_status'),
        ('core', '0001_initial'),
        ('payments', '0002_payment_webhook_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('payment_confirmed', 'Payment Manually Confirmed'), ('rental_activated', 'Rental Activated'), ('rental_completed', 'Rental Completed'), ('unit_assigned', 'Vehicle Unit Assigned'), ('unit_changed', 'Vehicle Unit Changed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_marked_waiting', 'Booking Marked Waiting'), ('profile_updated', 'Profile Updated')], max_length=40)),
                ('summary', models.CharField(max_length=500)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bookings.booking')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx'), models.Index(fields=['actor', '-created_at'], name='core_auditl_actor_i_502baf_idx'), models.Index(fields=['booking', '-created_at'], name='core_auditl_booking_c8e46c_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
