# Generated by Django 5.2.4 on 2026-08-14 08:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalDiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='The active global policy applied fleet-wide when a vehicle has no explicit override.  Only one policy can be default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental discount policy',
                'verbose_name_plural': 'Rental discount policies',
            },
        ),
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.PositiveIntegerField(default=1)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0–100) for rentals of min_days or more.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='core.rentaldiscountpolicy')),
            ],
            options={
                'ordering': ['min_days'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'min_days'), name='core_discounttier_unique_policy_min_days')],
            },
        ),
    ]
