# Generated by Django 4.2.30 on 2026-08-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_drivers_license_identitydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitydocument',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='identitydocument',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
