# Generated by Django 5.2.17 on 2026-08-08 14:12

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_identitydocument_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity_docs/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='front_image',
            field=models.ImageField(upload_to='identity_docs/front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size]),
        ),
    ]
