# Generated by Django 5.2.4 on 2026-08-10 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_identitydocument_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
