# Generated by Django 5.2.17 on 2026-08-11 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_identity_document_on_delete_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +639123456789).', regex='^\\+?[1-9]\\d{6,14}$')]),
        ),
    ]
