# Generated by Django 5.2.4 on 2026-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive failed login attempts. Reset on successful login.'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account is locked until this time. Null when not locked.', null=True),
        ),
    ]
