# Generated by Django 5.2.4 on 2026-08-13 03:00

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_account_lockout_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', help_text='How this account authenticates (email/password or Google).', max_length=10),
        ),
    ]
