# Generated by Django 5.2.4 on 2026-08-13 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_managers_user_auth_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit mobile number (e.g. 09123456789).', regex='^09\\d{9}$')]),
        ),
    ]
