# Generated by Django 5.2.4 on 2026-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, help_text='Increment to revoke all previously issued access tokens.'),
        ),
    ]
