# Generated by Django 5.2.4 on 2026-08-15 07:59

import apps.core.storage
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='back_image',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.private_identity_storage, upload_to='identity_docs/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size, apps.core.validators.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='front_image',
            field=models.ImageField(storage=apps.core.storage.private_identity_storage, upload_to='identity_docs/front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_image_size, apps.core.validators.validate_image_content]),
        ),
    ]
