# Generated by Django 5.2.17 on 2026-08-08 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicleunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('mpv', 'MPV'), ('van', 'Van'), ('pickup', 'Pickup'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon')], default='sedan', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
