# Generated by Django 5.2.4 on 2026-08-09 06:33

import apps.vehicles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.vehicles.models._validate_image_size, apps.vehicles.models._validate_image_content]),
        ),
    ]
