# Generated by Django 5.2.17 on 2026-08-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleunit',
            name='plate_number',
            field=models.CharField(help_text='Format: ABC-1234 or ABC-123 (3 letters, dash, 3-4 digits).', max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='vehicleunit',
            constraint=models.CheckConstraint(condition=models.Q(('plate_number__regex', '^[A-Z]{3}-\\d{3,4}$')), name='vehicles_vehicleunit_plate_number_format'),
        ),
    ]
