# Generated by Django 5.2.4 on 2026-08-12 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_plate_number_format_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Daily rental price (must be greater than 0).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
