# Generated by Django 5.2.4 on 2026-08-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rentaldiscountpolicy_discounttier'),
        ('vehicles', '0009_alter_vehicle_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='discount_policy',
            field=models.ForeignKey(blank=True, help_text='Optional discount policy override for this vehicle. Leave blank to use the global default policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.rentaldiscountpolicy'),
        ),
    ]
