# Generated by Django 5.2.4 on 2026-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='webhook_event_id',
            field=models.CharField(blank=True, help_text='PayMongo event ID for idempotency — prevents double-processing of webhooks.', max_length=100, null=True, unique=True),
        ),
    ]
