# Generated by Django 5.2.4 on 2026-08-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_webhook_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_session_id',
            field=models.CharField(blank=True, help_text='PayMongo Checkout Session ID — used to expire the session when the booking is cancelled while payment is pending.', max_length=120),
        ),
    ]
