# Generated by Django 5.2.4 on 2026-08-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_checkout_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='additional_charges',
        ),
    ]
